apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
specs:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
